### ISSUE TITLE
Problem in hydra

### ISSUE THREAD

**Issue by Dong142857** [tokaka22/GMAA#1]
Hi, thank you for your awesome work, I try to run the training script but stuck in 'hydra' package which i am not familiar with. Here is the running log:
```
Traceback (most recent call last):
  File "/raid/xjd/anaconda3/envs/ngp-torch/lib/python3.7/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
  File "/raid/xjd/anaconda3/envs/ngp-torch/lib/python3.7/site-packages/hydra/_internal/utils.py", line 357, in <lambda>
    task_name=task_name, config_search_path=search_path
  File "/raid/xjd/anaconda3/envs/ngp-torch/lib/python3.7/site-packages/hydra/_internal/hydra.py", line 62, in create_main_hydra2
    config_search_path=config_search_path
  File "/raid/xjd/anaconda3/envs/ngp-torch/lib/python3.7/site-packages/hydra/_internal/config_loader_impl.py", line 48, in __init__
    self.repository = ConfigRepository(config_search_path=config_search_path)
  File "/raid/xjd/anaconda3/envs/ngp-torch/lib/python3.7/site-packages/hydra/_internal/config_repository.py", line 65, in __init__
    self.initialize_sources(config_search_path)
  File "/raid/xjd/anaconda3/envs/ngp-torch/lib/python3.7/site-packages/hydra/_internal/config_repository.py", line 72, in initialize_sources
    scheme = self._get_scheme(search_path.path)
  File "/raid/xjd/anaconda3/envs/ngp-torch/lib/python3.7/site-packages/hydra/_internal/config_repository.py", line 143, in _get_scheme
    idx = path.find("://")
AttributeError: 'PosixPath' object has no attribute 'find'
```
Could you please suggest a solution for this problem?

**Comment by tokaka22** [comment]
It seems that the issue may be related to the version of a package. You can try checking the versions of the packages listed in my requirements.txt file and verifying that they are compatible with the version of Python you are using (I use 3.8). Alternatively, you can refer to the [lightning-hydra-template](https://github.com/ashleve/lightning-hydra-template) that I modified.

**Comment by Dong142857** [comment]
That's actually a version issue, thank you!
